on:
  pull_request:
  push:

env:
    GH_TOKEN: ${{ secrets.SecretToken }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:stable
          - devel
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.version }}
    - uses: extractions/setup-just@v2
    - name: Install dependencies
      run: |
        sudo apt install clang libclang-dev
    # Install DuckDB
    - name: Install DuckDB
      run: |
        wget https://github.com/duckdb/duckdb/releases/download/v1.1.2/libduckdb-linux-amd64.zip
        unzip libduckdb-linux-amd64.zip
        sudo mv libduckdb.so /usr/lib/
        sudo ldconfig
    - name: Test
      continue-on-error: ${{ matrix.version == 'devel' }}
      run: |
        nimble install -y
        just test

    - name: Generate documentation
      run: nim doc --project --out:docs src/nimdrake.nim

    - name: Upload documentation
      run: |
        git checkout --orphan gh-pages
        git --work-tree docs add --all
        git --work-tree docs commit -m "Deploy documentation"
        git push origin HEAD:gh-pages --force
        git checkout -f main
        git branch -D gh-pages
