on:
  pull_request:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: egor-tensin/setup-clang@v1
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v5
      - uses: extractions/setup-just@v2
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: nimble install -y
      - run: just test
