on:
  pull_request:
  push:

env:
    GH_TOKEN: ${{ secrets.SecretToken }}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v5
      - uses: extractions/setup-just@v2
      - name: Install dependencies
        run: |
          sudo apt install clang libclang-dev
      - uses: opt-nc/setup-duckdb-action@v1.0.8
        with:
         version: v1.1.2
      - name: wget
        uses: wei/wget@v1
        with:
         args: https://github.com/duckdb/duckdb/releases/download/v1.1.2/libduckdb-linux-amd64.zip
      - name: Extract some files
        run: 7z x libduckdb-linux-amd64.zip
      - run: nimble install -y
      - run: nimble test
