on:
  pull_request:
  push:

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version:
          - binary:stable
          - devel
        os:
          - ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: iffy/install-nim@v5
      with:
        version: ${{ matrix.version }}
    - uses: extractions/setup-just@v2
    - name: Install dependencies
      run: |
        sudo apt install clang libclang-dev
    # Install DuckDB
    - name: Install DuckDB
      run: |
        wget https://github.com/duckdb/duckdb/releases/download/v1.1.2/libduckdb-linux-amd64.zip
        unzip libduckdb-linux-amd64.zip
        sudo mv libduckdb.so /usr/lib/
        sudo ldconfig
    - name: Test
      continue-on-error: ${{ matrix.version == 'devel' }}
      run: |
        nimble install -y
        just test
  docs:
    runs-on: ubuntu-latest
    needs: tests # Wait for the tests job to complete
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v5
        with:
          version: binary:stable # Use a stable version for docs
      - uses: extractions/setup-just@v2
      - name: Install dependencies
        run: |
          sudo apt install clang libclang-dev
      # Install DuckDB
      - name: Install DuckDB
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v1.1.2/libduckdb-linux-amd64.zip
          unzip libduckdb-linux-amd64.zip
          sudo mv libduckdb.so /usr/lib/
          sudo ldconfig
      - name: Generate documentation
        run: |
          nimble install -y
          nim doc --project --out:docs src/nimdrake.nim
      - name: Upload documentation
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git --work-tree docs add --all
          git --work-tree docs commit -m "Deploy documentation"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/BontaVlad/NimDrake.git
          git push origin HEAD:gh-pages --force
          git checkout -f main
          git branch -D gh-pages
