on:
  pull_request:
  push:

env:
    GH_TOKEN: ${{ secrets.SecretToken }}
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iffy/install-nim@v5
      - uses: extractions/setup-just@v2
      - name: Install dependencies
        run: |
          sudo apt install clang libclang-dev
      - run: nimble install -y
      - run:
